// <auto-generated />
using System;
using Gastos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gastos.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201021125003_addCatIcons")]
    partial class addCatIcons
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gastos.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("IconID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<DateTime>("RegisterDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("TypeTransactionID")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CategoryID");

                    b.HasIndex("IconID");

                    b.HasIndex("TypeTransactionID");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Active = true,
                            IconID = 1,
                            Name = "Entretenimiento",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 679, DateTimeKind.Local).AddTicks(5224),
                            TypeTransactionID = 1
                        },
                        new
                        {
                            CategoryID = 2,
                            Active = true,
                            IconID = 2,
                            Name = "Salud",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 679, DateTimeKind.Local).AddTicks(9587),
                            TypeTransactionID = 1
                        },
                        new
                        {
                            CategoryID = 3,
                            Active = true,
                            IconID = 3,
                            Name = "Salario",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 680, DateTimeKind.Local).AddTicks(465),
                            TypeTransactionID = 2
                        },
                        new
                        {
                            CategoryID = 4,
                            Active = true,
                            IconID = 4,
                            Name = "Automóvil",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 680, DateTimeKind.Local).AddTicks(508),
                            TypeTransactionID = 1
                        },
                        new
                        {
                            CategoryID = 5,
                            Active = true,
                            IconID = 5,
                            Name = "Casa",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 680, DateTimeKind.Local).AddTicks(520),
                            TypeTransactionID = 1
                        },
                        new
                        {
                            CategoryID = 6,
                            Active = true,
                            IconID = 6,
                            Name = "Comida",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 680, DateTimeKind.Local).AddTicks(529),
                            TypeTransactionID = 1
                        });
                });

            modelBuilder.Entity("Gastos.Models.Icon", b =>
                {
                    b.Property<int>("IconID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("IconName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("RegisterDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("IconID");

                    b.ToTable("Icons","Cat");

                    b.HasData(
                        new
                        {
                            IconID = 7,
                            Active = true,
                            IconName = "fab fa-airbnb",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9532)
                        },
                        new
                        {
                            IconID = 8,
                            Active = true,
                            IconName = "fab fa-amazon",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9579)
                        },
                        new
                        {
                            IconID = 9,
                            Active = true,
                            IconName = "fab fa-apple",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9583)
                        },
                        new
                        {
                            IconID = 10,
                            Active = true,
                            IconName = "fas fa-baby",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9588)
                        },
                        new
                        {
                            IconID = 11,
                            Active = true,
                            IconName = "fas fa-bone",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9592)
                        },
                        new
                        {
                            IconID = 12,
                            Active = true,
                            IconName = "fas fa-ambulance",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9601)
                        },
                        new
                        {
                            IconID = 13,
                            Active = true,
                            IconName = "fas fa-bus-alt",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9605)
                        },
                        new
                        {
                            IconID = 14,
                            Active = true,
                            IconName = "fas fa-gas-pump",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9609)
                        },
                        new
                        {
                            IconID = 15,
                            Active = true,
                            IconName = "fas fa-taxi",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9613)
                        },
                        new
                        {
                            IconID = 16,
                            Active = true,
                            IconName = "fas fa-coffee",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9620)
                        },
                        new
                        {
                            IconID = 17,
                            Active = true,
                            IconName = "fas fa-cocktail",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9624)
                        },
                        new
                        {
                            IconID = 18,
                            Active = true,
                            IconName = "fas fa-birthday-cake",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9628)
                        },
                        new
                        {
                            IconID = 19,
                            Active = true,
                            IconName = "fas fa-tshirt",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9632)
                        },
                        new
                        {
                            IconID = 20,
                            Active = true,
                            IconName = "fas fa-wifi",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9636)
                        },
                        new
                        {
                            IconID = 21,
                            Active = true,
                            IconName = "fas fa-tv",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9640)
                        },
                        new
                        {
                            IconID = 22,
                            Active = true,
                            IconName = "fas fa-laptop",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9644)
                        },
                        new
                        {
                            IconID = 23,
                            Active = true,
                            IconName = "fas fa-money-bill-wave",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9648)
                        },
                        new
                        {
                            IconID = 24,
                            Active = true,
                            IconName = "fas fa-dollar-sign",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9653)
                        },
                        new
                        {
                            IconID = 25,
                            Active = true,
                            IconName = "fas fa-graduation-cap",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9658)
                        },
                        new
                        {
                            IconID = 26,
                            Active = true,
                            IconName = "fas fa-credit-card",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9662)
                        },
                        new
                        {
                            IconID = 27,
                            Active = true,
                            IconName = "fas fa-heartbeat",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9666)
                        },
                        new
                        {
                            IconID = 28,
                            Active = true,
                            IconName = "fas fa-bone",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9670)
                        },
                        new
                        {
                            IconID = 29,
                            Active = true,
                            IconName = "fas fa-pizza-slice",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9674)
                        },
                        new
                        {
                            IconID = 30,
                            Active = true,
                            IconName = "fas fa-dice",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9678)
                        },
                        new
                        {
                            IconID = 31,
                            Active = true,
                            IconName = "fab fa-playstation",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9682)
                        },
                        new
                        {
                            IconID = 32,
                            Active = true,
                            IconName = "fab fa-steam",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9687)
                        },
                        new
                        {
                            IconID = 33,
                            Active = true,
                            IconName = "fab fa-xbox",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9691)
                        },
                        new
                        {
                            IconID = 34,
                            Active = true,
                            IconName = "fas fa-hand-holding-usd",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9695)
                        },
                        new
                        {
                            IconID = 35,
                            Active = true,
                            IconName = "fas fa-ambulance",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9699)
                        },
                        new
                        {
                            IconID = 36,
                            Active = true,
                            IconName = "far fa-hospital",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9704)
                        },
                        new
                        {
                            IconID = 37,
                            Active = true,
                            IconName = "fas fa-gift",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9708)
                        },
                        new
                        {
                            IconID = 38,
                            Active = true,
                            IconName = "fas fa-dumbbell",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9712)
                        },
                        new
                        {
                            IconID = 39,
                            Active = true,
                            IconName = "fas fa-house-user",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9716)
                        },
                        new
                        {
                            IconID = 40,
                            Active = true,
                            IconName = "fas fa-headphones",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9721)
                        },
                        new
                        {
                            IconID = 1,
                            Active = true,
                            IconName = "fas fa-glass-cheers",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 674, DateTimeKind.Local).AddTicks(6785)
                        },
                        new
                        {
                            IconID = 2,
                            Active = true,
                            IconName = "fas fa-hospital",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9036)
                        },
                        new
                        {
                            IconID = 3,
                            Active = true,
                            IconName = "fas fa-wallet",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9121)
                        },
                        new
                        {
                            IconID = 4,
                            Active = true,
                            IconName = "fas fa-car",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9133)
                        },
                        new
                        {
                            IconID = 5,
                            Active = true,
                            IconName = "fas fa-house-user",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9140)
                        },
                        new
                        {
                            IconID = 6,
                            Active = true,
                            IconName = "fas fa-utensils",
                            RegisterDate = new DateTime(2020, 10, 21, 7, 50, 2, 678, DateTimeKind.Local).AddTicks(9147)
                        });
                });

            modelBuilder.Entity("Gastos.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<int>("TypeTransactionID")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TransactionID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("TypeTransactionID");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Gastos.Models.TypeTransaction", b =>
                {
                    b.Property<int>("TypeTransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeTransactionID");

                    b.ToTable("TypeTransactions");

                    b.HasData(
                        new
                        {
                            TypeTransactionID = 1,
                            Name = "Gasto"
                        },
                        new
                        {
                            TypeTransactionID = 2,
                            Name = "Ingreso"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Gastos.Models.Category", b =>
                {
                    b.HasOne("Gastos.Models.Icon", "Icon")
                        .WithMany()
                        .HasForeignKey("IconID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gastos.Models.TypeTransaction", "TypeTransaction")
                        .WithMany("Categories")
                        .HasForeignKey("TypeTransactionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Gastos.Models.Transaction", b =>
                {
                    b.HasOne("Gastos.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gastos.Models.TypeTransaction", "TypeTransaction")
                        .WithMany("Transactions")
                        .HasForeignKey("TypeTransactionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
