// <auto-generated />
using System;
using Gastos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gastos.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201230014553_NuevosIconos")]
    partial class NuevosIconos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gastos.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("IconID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<DateTime>("RegisterDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("TypeTransactionID")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CategoryID");

                    b.HasIndex("IconID");

                    b.HasIndex("TypeTransactionID");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Active = true,
                            IconID = 1,
                            Name = "Entretenimiento",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(521),
                            TypeTransactionID = 1
                        },
                        new
                        {
                            CategoryID = 2,
                            Active = true,
                            IconID = 2,
                            Name = "Salud",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5090),
                            TypeTransactionID = 1
                        },
                        new
                        {
                            CategoryID = 3,
                            Active = true,
                            IconID = 3,
                            Name = "Salario",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5251),
                            TypeTransactionID = 2
                        },
                        new
                        {
                            CategoryID = 4,
                            Active = true,
                            IconID = 4,
                            Name = "Automóvil",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5256),
                            TypeTransactionID = 1
                        },
                        new
                        {
                            CategoryID = 5,
                            Active = true,
                            IconID = 5,
                            Name = "Casa",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5261),
                            TypeTransactionID = 1
                        },
                        new
                        {
                            CategoryID = 6,
                            Active = true,
                            IconID = 6,
                            Name = "Comida",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5266),
                            TypeTransactionID = 1
                        },
                        new
                        {
                            CategoryID = 7,
                            Active = true,
                            IconID = 8,
                            Name = "Amazon",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5271),
                            TypeTransactionID = 1
                        },
                        new
                        {
                            CategoryID = 8,
                            Active = true,
                            IconID = 10,
                            Name = "Bebé",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5275),
                            TypeTransactionID = 1
                        },
                        new
                        {
                            CategoryID = 9,
                            Active = true,
                            IconID = 12,
                            Name = "Emergencia",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5279),
                            TypeTransactionID = 1
                        },
                        new
                        {
                            CategoryID = 10,
                            Active = true,
                            IconID = 13,
                            Name = "Transporte",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5283),
                            TypeTransactionID = 1
                        },
                        new
                        {
                            CategoryID = 11,
                            Active = true,
                            IconID = 14,
                            Name = "Gasolina",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5288),
                            TypeTransactionID = 1
                        },
                        new
                        {
                            CategoryID = 12,
                            Active = true,
                            IconID = 15,
                            Name = "Taxi",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5292),
                            TypeTransactionID = 1
                        },
                        new
                        {
                            CategoryID = 13,
                            Active = true,
                            IconID = 16,
                            Name = "Café",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5297),
                            TypeTransactionID = 1
                        },
                        new
                        {
                            CategoryID = 14,
                            Active = true,
                            IconID = 17,
                            Name = "Alcohol",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5301),
                            TypeTransactionID = 1
                        },
                        new
                        {
                            CategoryID = 15,
                            Active = true,
                            IconID = 18,
                            Name = "Cumpleaños",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5305),
                            TypeTransactionID = 1
                        },
                        new
                        {
                            CategoryID = 16,
                            Active = true,
                            IconID = 19,
                            Name = "Ropa",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5309),
                            TypeTransactionID = 1
                        },
                        new
                        {
                            CategoryID = 17,
                            Active = true,
                            IconID = 20,
                            Name = "Wifi",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5313),
                            TypeTransactionID = 1
                        },
                        new
                        {
                            CategoryID = 18,
                            Active = true,
                            IconID = 21,
                            Name = "Tv",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5318),
                            TypeTransactionID = 1
                        },
                        new
                        {
                            CategoryID = 19,
                            Active = true,
                            IconID = 22,
                            Name = "Computación",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5322),
                            TypeTransactionID = 1
                        },
                        new
                        {
                            CategoryID = 20,
                            Active = true,
                            IconID = 23,
                            Name = "Honorarios",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5326),
                            TypeTransactionID = 2
                        },
                        new
                        {
                            CategoryID = 21,
                            Active = true,
                            IconID = 26,
                            Name = "TDC",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5330),
                            TypeTransactionID = 1
                        },
                        new
                        {
                            CategoryID = 22,
                            Active = true,
                            IconID = 34,
                            Name = "Préstamo",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5335),
                            TypeTransactionID = 2
                        },
                        new
                        {
                            CategoryID = 23,
                            Active = true,
                            IconID = 38,
                            Name = "Gimnasio",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5339),
                            TypeTransactionID = 1
                        },
                        new
                        {
                            CategoryID = 24,
                            Active = true,
                            IconID = 40,
                            Name = "Accesorios",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5343),
                            TypeTransactionID = 1
                        },
                        new
                        {
                            CategoryID = 25,
                            Active = true,
                            IconID = 41,
                            Name = "Ventas",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5347),
                            TypeTransactionID = 2
                        },
                        new
                        {
                            CategoryID = 26,
                            Active = true,
                            IconID = 42,
                            Name = "Rendimientos",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5352),
                            TypeTransactionID = 2
                        },
                        new
                        {
                            CategoryID = 27,
                            Active = true,
                            IconID = 43,
                            Name = "Inversión",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 505, DateTimeKind.Local).AddTicks(5356),
                            TypeTransactionID = 2
                        });
                });

            modelBuilder.Entity("Gastos.Models.Icon", b =>
                {
                    b.Property<int>("IconID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("IconName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("RegisterDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("IconID");

                    b.ToTable("Icons","Cat");

                    b.HasData(
                        new
                        {
                            IconID = 7,
                            Active = true,
                            IconName = "fab fa-airbnb",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5501)
                        },
                        new
                        {
                            IconID = 8,
                            Active = true,
                            IconName = "fab fa-amazon",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5554)
                        },
                        new
                        {
                            IconID = 9,
                            Active = true,
                            IconName = "fab fa-apple",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5560)
                        },
                        new
                        {
                            IconID = 10,
                            Active = true,
                            IconName = "fas fa-baby",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5563)
                        },
                        new
                        {
                            IconID = 11,
                            Active = true,
                            IconName = "fas fa-bone",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5568)
                        },
                        new
                        {
                            IconID = 12,
                            Active = true,
                            IconName = "fas fa-ambulance",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5576)
                        },
                        new
                        {
                            IconID = 13,
                            Active = true,
                            IconName = "fas fa-bus-alt",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5580)
                        },
                        new
                        {
                            IconID = 14,
                            Active = true,
                            IconName = "fas fa-gas-pump",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5583)
                        },
                        new
                        {
                            IconID = 15,
                            Active = true,
                            IconName = "fas fa-taxi",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5587)
                        },
                        new
                        {
                            IconID = 16,
                            Active = true,
                            IconName = "fas fa-coffee",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5593)
                        },
                        new
                        {
                            IconID = 17,
                            Active = true,
                            IconName = "fas fa-cocktail",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5597)
                        },
                        new
                        {
                            IconID = 18,
                            Active = true,
                            IconName = "fas fa-birthday-cake",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5601)
                        },
                        new
                        {
                            IconID = 19,
                            Active = true,
                            IconName = "fas fa-tshirt",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5605)
                        },
                        new
                        {
                            IconID = 20,
                            Active = true,
                            IconName = "fas fa-wifi",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5609)
                        },
                        new
                        {
                            IconID = 21,
                            Active = true,
                            IconName = "fas fa-tv",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5612)
                        },
                        new
                        {
                            IconID = 22,
                            Active = true,
                            IconName = "fas fa-laptop",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5617)
                        },
                        new
                        {
                            IconID = 23,
                            Active = true,
                            IconName = "fas fa-money-bill-wave",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5621)
                        },
                        new
                        {
                            IconID = 24,
                            Active = true,
                            IconName = "fas fa-dollar-sign",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5626)
                        },
                        new
                        {
                            IconID = 25,
                            Active = true,
                            IconName = "fas fa-graduation-cap",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5630)
                        },
                        new
                        {
                            IconID = 26,
                            Active = true,
                            IconName = "fas fa-credit-card",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5634)
                        },
                        new
                        {
                            IconID = 27,
                            Active = true,
                            IconName = "fas fa-heartbeat",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5637)
                        },
                        new
                        {
                            IconID = 28,
                            Active = true,
                            IconName = "fas fa-bone",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5641)
                        },
                        new
                        {
                            IconID = 29,
                            Active = true,
                            IconName = "fas fa-pizza-slice",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5645)
                        },
                        new
                        {
                            IconID = 30,
                            Active = true,
                            IconName = "fas fa-dice",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5649)
                        },
                        new
                        {
                            IconID = 31,
                            Active = true,
                            IconName = "fab fa-playstation",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5653)
                        },
                        new
                        {
                            IconID = 32,
                            Active = true,
                            IconName = "fab fa-steam",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5657)
                        },
                        new
                        {
                            IconID = 33,
                            Active = true,
                            IconName = "fab fa-xbox",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5662)
                        },
                        new
                        {
                            IconID = 34,
                            Active = true,
                            IconName = "fas fa-hand-holding-usd",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5668)
                        },
                        new
                        {
                            IconID = 35,
                            Active = true,
                            IconName = "fas fa-ambulance",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5674)
                        },
                        new
                        {
                            IconID = 36,
                            Active = true,
                            IconName = "far fa-hospital",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5680)
                        },
                        new
                        {
                            IconID = 37,
                            Active = true,
                            IconName = "fas fa-gift",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5686)
                        },
                        new
                        {
                            IconID = 38,
                            Active = true,
                            IconName = "fas fa-dumbbell",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5693)
                        },
                        new
                        {
                            IconID = 39,
                            Active = true,
                            IconName = "fas fa-house-user",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5699)
                        },
                        new
                        {
                            IconID = 40,
                            Active = true,
                            IconName = "fas fa-headphones",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5738)
                        },
                        new
                        {
                            IconID = 1,
                            Active = true,
                            IconName = "fas fa-glass-cheers",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(3985)
                        },
                        new
                        {
                            IconID = 2,
                            Active = true,
                            IconName = "fas fa-hospital",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5050)
                        },
                        new
                        {
                            IconID = 3,
                            Active = true,
                            IconName = "fas fa-wallet",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5087)
                        },
                        new
                        {
                            IconID = 4,
                            Active = true,
                            IconName = "fas fa-car",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5095)
                        },
                        new
                        {
                            IconID = 5,
                            Active = true,
                            IconName = "fas fa-house-user",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5101)
                        },
                        new
                        {
                            IconID = 6,
                            Active = true,
                            IconName = "fas fa-utensils",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5107)
                        },
                        new
                        {
                            IconID = 41,
                            Active = true,
                            IconName = "fas fa-chart-bar",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5113)
                        },
                        new
                        {
                            IconID = 42,
                            Active = true,
                            IconName = "fas fa-chart-pie",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5119)
                        },
                        new
                        {
                            IconID = 43,
                            Active = true,
                            IconName = "fas fa-chart-line",
                            RegisterDate = new DateTime(2020, 12, 29, 19, 45, 52, 504, DateTimeKind.Local).AddTicks(5125)
                        });
                });

            modelBuilder.Entity("Gastos.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<int>("TypeTransactionID")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TransactionID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("TypeTransactionID");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Gastos.Models.TypeTransaction", b =>
                {
                    b.Property<int>("TypeTransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeTransactionID");

                    b.ToTable("TypeTransactions");

                    b.HasData(
                        new
                        {
                            TypeTransactionID = 1,
                            Name = "Gasto"
                        },
                        new
                        {
                            TypeTransactionID = 2,
                            Name = "Ingreso"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Gastos.Models.Category", b =>
                {
                    b.HasOne("Gastos.Models.Icon", "Icon")
                        .WithMany()
                        .HasForeignKey("IconID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gastos.Models.TypeTransaction", "TypeTransaction")
                        .WithMany("Categories")
                        .HasForeignKey("TypeTransactionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Gastos.Models.Transaction", b =>
                {
                    b.HasOne("Gastos.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gastos.Models.TypeTransaction", "TypeTransaction")
                        .WithMany("Transactions")
                        .HasForeignKey("TypeTransactionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
